parameters:
  cors.config:
    enabled: true
    allowedHeaders: ["x-csrf-token", "content-type", "accept", "authorization"]
    allowedMethods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
    allowedOrigins: ["http://localhost:3000"]
    exposedHeaders: true
    maxAge: 1000
    supportsCredentials: true

  # Session configuration (optional, keeps sessions stable)
  session.storage.options:
    gc_probability: 1
    gc_divisor: 100
    gc_maxlifetime: 200000
    cookie_lifetime: 2000000
    cookie_samesite: Lax
    name_suffix: ""

  # Twig configuration (optional)
  twig.config:
    debug: false
    auto_reload: null
    cache: true
    allowed_file_extensions:
      - css
      - html
      - js
      - svg
      - twig
